network:
  version: 2
  ethernets:
    id0:
      match:
        name: "en*"
      dhcp4: true
      dhcp-identifier: mac
    id1:
      match:
        name: "eth*"
      dhcp4: true
      dhcp-identifier: mac
